import type { Metadata } from "next";
import { BookOpenCheck, Clock3, Sparkles, Users } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AppBreadcrumb } from "@/components/app/AppBreadcrumb";
import { AppPageHeader } from "@/components/app/AppPageHeader";
import { UnifiedAppShell } from "@/components/app/UnifiedAppShell";
import { getCurrentProfile, requireAuth } from "@/lib/auth/server";
import { getUnifiedCourseRelations } from "@/lib/unified-course-relations";
import { createPageMetadata } from "@/lib/seo";
export const dynamic = "force-dynamic";
export const metadata: Metadata = createPageMetadata({ title: "Collaboratif", description: "Les fonctions collaboratives réelles et leurs prochaines étapes.", path: "/app/collaborative", noIndex: true });
export default async function CollaborativePage() { await requireAuth("/app/collaborative"); const profile = await getCurrentProfile(); if (!profile) redirect("/access-denied?reason=profile&next=%2Fapp%2Fcollaborative"); const relations = await getUnifiedCourseRelations(profile); const manageable = relations.filter((relation) => relation.capabilities.includes("edit")); return <UnifiedAppShell profile={profile}><div className="app-page unified-collaborative"><AppBreadcrumb items={[{ label: "Accueil", href: "/app" }, { label: "Collaboratif" }]} /><AppPageHeader eyebrow="Collaboratif" title="Ce qui est réellement disponible" description="La collaboration s'appuie sur des données existantes, sans avatars, messages ou activité inventés." /><section className="unified-real-grid" aria-label="Fonctionnalités collaboratives réelles">{manageable.length ? <><article><Users size={20} aria-hidden="true" /><h2>Inscrits et progression</h2><p>Consultez les inscrits, leur progression et leur dernière activité pour les parcours que vous gérez.</p><Link href="/app/teacher/students">Ouvrir le suivi</Link></article><article><BookOpenCheck size={20} aria-hidden="true" /><h2>Publication</h2><p>Les états brouillon, publié, public, non répertorié ou privé restent gérés dans vos parcours.</p><Link href="/app/teacher/courses">Gérer mes parcours</Link></article></> : <p className="unified-empty">Aucun parcours que vous gérez n'est accessible pour le moment.</p>}</section><section className="unified-future-grid" aria-label="Fonctionnalités collaboratives à venir"><article><Clock3 size={20} aria-hidden="true" /><h2>Contributions</h2><p>Proposer et réviser des améliorations.</p><span>À venir</span></article><article><Sparkles size={20} aria-hidden="true" /><h2>Discussions contextuelles</h2><p>Échanger dans un parcours, une leçon ou une contribution.</p><span>À venir</span></article><article><Users size={20} aria-hidden="true" /><h2>Invitations et remix</h2><p>Partager des rôles et préserver la provenance.</p><span>À venir</span></article></section></div></UnifiedAppShell>; }